FROM php:5.6-apache

RUN set -x \
    && apt-get update \
    && apt-get install -y libsybdb5 freetds-dev locales \
    && ln -s /usr/lib/x86_64-linux-gnu/libsybdb.so /usr/lib/ \
    && echo "en_US.UTF-8 UTF-8" > /etc/locale.gen \
    && locale-gen \
    && docker-php-ext-install -j$(nproc) pdo_dblib bcmath  \
    && pecl install redis \
    && docker-php-ext-enable redis \
    && rm -rf /var/lib/apt/lists/*